### ISSUE TITLE
The year heading is off by 1

### ISSUE THREAD

**Issue by neuroradiology** [nixcloud/pankat#5]
On your page:

https://lastlog.de/blog/posts.html

The headings start with the year 2017, but the posts under that heading are from 2016.

Could there be an index-starting-at-0 bug?

(Not sure if it's in the pankat platform or specific to that particular install)

![pankat-timeline](https://cloud.githubusercontent.com/assets/8550951/19434669/e0fed0ee-9434-11e6-8a8b-fad2112802d6.png)

**Comment by qknight** [comment]
one can see it either the way you describe it. the alternative would be to see it as a timeline and that the event, like tuebix, happened somewhere between 2016 and 2017.

the thing is, i kind of need a 2017 box in that timeline or i can't expand the elements below it. didn't find any other timeline javascript implementation, which was as feature rich and yet simple, as this one.

https://technotarek.com/timeliner/

if you really feel this breaks usability then we should search for a solution unless so, please close this issue.

thanks for your feedback!

**Comment by neuroradiology** [comment]
no objection
